"""
상수 정의 모듈
"""

DEFAULT_TIMEOUT = 120  
SHORT_TIMEOUT = 30  
MEDIUM_TIMEOUT = 60  
LONG_TIMEOUT = 180  
VERY_LONG_TIMEOUT = 300  

DEFAULT_RETRY_COUNT = 2  
MAX_RETRY_COUNT = 5  
MIN_BACKOFF_SECONDS = 1  
MAX_BACKOFF_SECONDS = 10  

MAX_REACT_ITERATIONS = 30  
MAX_SAME_ACTION_RETRIES = 2  
MAX_SAME_TOOL_CALLS = 5  

LLM_TEMPERATURE_DEFAULT = 0.0 
LLM_TEMPERATURE_CREATIVE = 0.7 

LLM_MAX_TOKENS_DEFAULT = 4096
LLM_MAX_TOKENS_LARGE = 8192

RAG_TOP_K = 10  
RAG_SIMILARITY_THRESHOLD = 0.5  

PREVIEW_MAX_LENGTH = 1000  
PREVIEW_MAX_LINES = 50  

RETRYABLE_ERROR_PATTERNS = [
    "connection",
    "timeout",
    "temporary",
    "unavailable",
    "network",
    "refused",
    "reset",
]

DISK_IMAGE_EXTENSIONS = [".dd", ".raw", ".img", ".e01", ".aff"]
PE_FILE_EXTENSIONS = [".exe", ".dll", ".sys"]
LOG_FILE_EXTENSIONS = [".log", ".evtx", ".txt"]
ARCHIVE_EXTENSIONS = [".zip", ".tar", ".gz", ".7z"]

COLLECTION_AGENT_STATES = "agent_states"
COLLECTION_MCP_EVIDENCES = "mcp_evidences"
COLLECTION_MCP_CAPABILITIES = "mcp_capabilities"

SEPARATOR = "-" * 60
DOUBLE_SEPARATOR = "=" * 60